name: Java CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        java-version: [ '17' ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install graphviz
        run: sudo apt-get install graphviz
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
      - name: Build with Gradle
        run: ./gradlew build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Build documentation
        run: ./gradlew :plantUml9:docs
      - name: Prepare generated JavaDoc for artifact upload
        run: mv ../jdrupes-taglets.gh-pages .
      - uses: actions/upload-artifact@v3
        with:
          name: docs
          path: jdrupes-taglets.gh-pages/plantuml-taglet/javadoc/
