name: Java CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        java-version: [ '11', '17', '20' ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install graphviz
        run: sudo apt-get install graphviz
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
      - name: Build with Gradle
        run: ./gradlew build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
